language: go
cache: false

go:
  - 1.13.x

notifications:
  email: false

stages:
  - check
  - build
  - test
  - run

jobs:
  include:
    - stage: check
      script:
        - go install github.com/golangci/golangci-lint/cmd/golangci-lint
        - golangci-lint run       # run a bunch of code checkers/linters in parallel

    - stage: build
      script:
        - go build ./...          # build the project

    - stage: test
      os: linux
      script:
        - go test -v -race ./...  # Run all the tests with the race detector enabled

    - stage: test
      os: osx
      script:
        - go test -v -race ./...  # Run all the tests with the race detector enabled

    - stage: test
      os: windows
      script:
        - go test -v -race ./...  # Run all the tests with the race detector enabled

    # Run two test plans with and without docker just to confirm they complete
    - stage: run
      os: linux
      script:
        - go run main.go run smlbench/simple-add --builder=exec:go --runner=local:exec

    - stage: run
      os: osx
      script:
        - go run main.go run smlbench/simple-add --builder=exec:go --runner=local:exec

    - stage: run
      os: windows
      script:
        - go run main.go run smlbench/simple-add --builder=exec:go --runner=local:exec

    - stage: run
      os: linux
      script:
        - go run main.go run smlbench/simple-add --builder=docker:go --runner=local:docker

    - stage: run
      os: osx
      script:
        - go run main.go run smlbench/simple-add --builder=docker:go --runner=local:docker

    - stage: run
      os: windows
      script:
        - go run main.go run smlbench/simple-add --builder=docker:go --runner=local:docker
