language: go
cache: false

go:
  - 1.13.x

git:
  depth: 1

notifications:
  email: false

os:
  - linux
  - osx
  - windows

stages:
  - check
  - build
  - test
  - run

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

jobs:
  include:
    - stage: check
      script:
        - golangci-lint run       # run a bunch of code checkers/linters in parallel

    - stage: build
      script:
        - go build ./...          # build the project

    - stage: test
      script:
        - go test -v -race ./...  # Run all the tests with the race detector enabled

    - stage: run                  # Run two test plans with and without docker just to confirm they complete
      script:
        - go run main.go run smlbench/simple-add --builder=exec:go --runner=local:exec
        - go run main.go run smlbench/simple-add --builder=docker:go --runner=local:docker
