name = "ipfs-e2e"
# hashicorp/go-getter URLs, so in the future we can support fetching test plans
# from GitHub.
source_path = "file://${TESTGROUND_SRCDIR}/plans/ipfs-e2e"

[defaults]
builder = "exec:go"
runner = "local:exec"

[build_strategies."docker:go"]
enabled = true
go_version = "1.13"
module_path = "github.com/ipfs/testground/plans/ipfs-e2e"
exec_pkg = "."
go_ipfs_version = "0.4.22"

[build_strategies."exec:go"]
enabled = true
module_path = "github.com/ipfs/testground/plans/ipfs-e2e"
exec_pkg = "."

[run_strategies."local:docker"]
enabled = true

[run_strategies."local:exec"]
enabled = true

[run_strategies."cluster:swarm"]
enabled = true

[[testcases]]
name = "e2e"
instances = { min = 1, max = 200, default = 1 }
  [testcases.params]
  param1 = { type = "int", desc = "some param 1", unit = "widgets", default=1 }
